baseURL: "https://vgjm.github.io/"
title: vgjm
theme: PaperMod

paginate: 5

params:
  # Home page
  defaultTheme: dark
  title: vgjm
  description: "Welcome to my blog \U0001F44B"

  assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"

  # home-info mode
  homeInfoParams:
    Title: "vgjm"
    Content: "Welcome to my blog \U0001F44B"

  # Metadata
  env: production
  keywords: [vgjm, developer, go, blog]

  # Posts config
  ShowBreadCrumbs: true
  DateFormat: "January 2, 2006"
  author: vgjm
  editPost:
    URL: "https://github.com/vgjm/website/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
  ShowToc: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  hideFooter: true

  label:
    text: "Home"
    iconHeight: 35

  socialIcons:
    - name: email
      url: "mailto://vgjm456@qq.com"
    - name: github
      url: "https://github.com/vgjm"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/17314397/vgjm"



menu:
  main:
    - identifier: Posts
      name: Posts
      url: /posts
      weight: 30