baseURL = 'http://vgjm.github.io/'
languageCode = 'en-us'
title = "vgjm"
theme = "manis"

# Copyright notice. Note: You can use HTML tag here
copyright = "&copy; 2022 vgjm"
pluralizeListTitles = false

# Minimum number of posts before paginate navigation show up
paginate = 10

[menu]
        [[menu.main]]
                name = "Home"
                url = "/"
        [[menu.main]]
                name = "Posts"
                url = "/posts/"
[params]

        # Site's Tagline (Subtitle or Keyword)
        tagline = "Jinming Guo"
        # If true give attribution to this theme
        themeAttrib = false
        # URL to license file, can be outside of your domain
        licenseURL = "https://github.com/vgjm/license/blob/main/README.md"

        # 404 Configuration
        head404 = "Sorry, I can't find what you want."
        sub404 = "Back to <a href='/'>Home</a>."

        # Color of your website's accent
        colorTheme = "#ff6565"
        # Maximum number of item in Latest Posts or Works
        latestCount = 10
        # Path to site's favicon image
        faviconImg = ""
        # Date format in item list
        dateFmt = "Jan 02, 2006"

        # Code Highlighting (HighlightJS)
        highlightJs = false
        highlightJsLanguages = [ "go" ]
        highlightJsStyle = "ocean"

        # Social Links
        email = "vgjm456@qq.com"
        github = "https://github.com/vgjm/"

