name: Build 

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: '0.97.3'
      BRANCH: public
      DIR: build
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Install hugo
      run: |
        cd ..
        curl -LO 'https://github.com/gohugoio/hugo/releases/download/v'$VERSION'/hugo_'$VERSION'_Linux-64bit.tar.gz'
        tar -zxf 'hugo_'$VERSION'_Linux-64bit.tar.gz'
        mv hugo /usr/local/bin/
        hugo version
    - name: Create local changes
      run: |
        hugo -d build
    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "github-actions"
        git add $DIR
        git commit -m "Auto build" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: $BRANCH